### ISSUE TITLE
add docs page to replace individual readme files

### ISSUE THREAD

**Issue by bartvanosnabrugge** [CH-Earth/summaWorkflow_public#103]
a docs page is the standard for successful packages that are used by multiple users, giving a better overview and can be sectioned to show different parts of the workflow in one doc.

some examples:
https://deltares.github.io/hydromt/latest/
http://xarray.pydata.org/en/stable/
https://rasterio.readthedocs.io/en/latest/

**Comment by wknoben** [comment]
Currently, relevant info is in READMEs in each folder because:
- These can be viewed at the same time as one navigates the folders on Github
- Relevant information is contained next to the scripts it pertains to, increasing the chance that users will find and read it, also after cloning the code locally
- Keeping docs up-to-date is a bit more labor-intensive than updating a readme that's next to the script one just changed

I don't think the code here is so large that the READMEs have become unwieldy. Are there concrete examples of where a better overview is needed in a way that docs can provide but README files cannot?
