### ISSUE TITLE
SUMMA run error

### ISSUE THREAD

**Issue by solosue** [CH-Earth/summaWorkflow_public#99]
Hi, I had an error after my summa work ran for years.  Do you have any idea why this occur and how to solve this?  Thabk you so much!

The error info is pasted below.

STOP 1
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
STOP 1
HDF5: infinite loop closing library
      R,D,G,A,S,T,D,G,S,F,D,S,T,F,FD,P,FD,P,FD,P,E,E,SL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL

 [mpiexec@lab16]HYD_pmcd_pmiserv_proxy_init_cb (pm/pmiserv/pmiserv_cb.c:467): cannot find proxy with ID 66326
[mpiexec@lab16] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@lab16] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:198): error waiting for event
[mpiexec@lab16] main (ui/mpich/mpiexec.c:340): process manager error waiting for completion

**Comment by wknoben** [comment]
I have not seen this before but a quick search suggests that this is related to using an older HDF5 library version. 

- Same question: https://forum.hdfgroup.org/t/hdf5-infinite-loop-closing-library/5176
- Git PR on the HDF5 page that supposedly addresses this: https://github.com/HDFGroup/hdf5/commit/f808c108ed0315f115a7c69cbd8ee95032a64b34

I would suggest updating your HDF5 library and retrying. Please report back if this solves your problem so that this issue can be closed.

**Comment by wknoben** [comment]
Hi, I assume this has been solved and will close the issue. Feel free to get in touch if things are still not cooperating.
